# Generated by Django 3.2.12 on 2023-03-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CarSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airbags', models.PositiveIntegerField()),
                ('number_of_airbags', models.PositiveIntegerField()),
                ('antilock_braking_system', models.BooleanField()),
                ('electronic_stability_control', models.BooleanField()),
                ('rearview_camera', models.BooleanField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarPerfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('top_speed', models.PositiveIntegerField()),
                ('fuel_economy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_parking_brake', models.BooleanField()),
                ('automatic_parking_assist', models.BooleanField()),
                ('night_vision_assist', models.BooleanField()),
                ('adaptive_cruise_control', models.BooleanField()),
                ('digital_cockpit', models.BooleanField()),
                ('blind_spot_monitor', models.BooleanField()),
                ('hill_assist', models.BooleanField()),
                ('tyre_pressure_monitoring_system', models.BooleanField()),
                ('automatic_climate_control', models.BooleanField()),
                ('dual_zone_climate_control', models.BooleanField()),
                ('anti_pinch_power_windows', models.BooleanField()),
                ('heated_orvm', models.BooleanField()),
                ('hill_descent_control', models.BooleanField()),
                ('apple_car_play', models.BooleanField()),
                ('hands_free_tailgate', models.BooleanField()),
                ('mild_hybrid', models.BooleanField()),
                ('driving_mode', models.BooleanField()),
                ('real_time_vehicle_tracking', models.BooleanField()),
                ('engine_immobilizer', models.BooleanField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car')),
            ],
        ),
    ]
