# Generated by Django 3.2.12 on 2023-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='cardimension',
            options={'verbose_name': 'Car Dimension', 'verbose_name_plural': 'Car Dimensions'},
        ),
        migrations.AlterModelOptions(
            name='carfeature',
            options={'verbose_name': 'Car Feature', 'verbose_name_plural': 'Car Features'},
        ),
        migrations.AlterModelOptions(
            name='carperfomance',
            options={'verbose_name': 'Car Perfomance', 'verbose_name_plural': 'Car Perfomances'},
        ),
        migrations.AlterModelOptions(
            name='carsafety',
            options={'verbose_name': 'Car Safety', 'verbose_name_plural': 'Car Safeties'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='cardimension',
            name='height',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='cardimension',
            name='length',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cardimension',
            name='width',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='adaptive_cruise_control',
            field=models.BooleanField(default=False, help_text='adaptive_cruise_control supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='anti_pinch_power_windows',
            field=models.BooleanField(default=False, help_text='anti_pinch_power_windows supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='apple_car_play',
            field=models.BooleanField(default=False, help_text='apple_car_play supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='automatic_climate_control',
            field=models.BooleanField(default=False, help_text='automatic_climate_control supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='automatic_parking_assist',
            field=models.BooleanField(default=False, help_text='automatic_parking_assist supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='blind_spot_monitor',
            field=models.BooleanField(default=False, help_text='blind_spot_monitor supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='digital_cockpit',
            field=models.BooleanField(default=False, help_text='digital_cockpit supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='driving_mode',
            field=models.BooleanField(default=False, help_text='driving_mode supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='dual_zone_climate_control',
            field=models.BooleanField(default=False, help_text='dual_zone_climate_control supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='electronic_parking_brake',
            field=models.BooleanField(default=False, help_text='electronic_parking_brake supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='engine_immobilizer',
            field=models.BooleanField(default=False, help_text='engine_immobilizer supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='hands_free_tailgate',
            field=models.BooleanField(default=False, help_text='hands_free_tailgate supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='heated_orvm',
            field=models.BooleanField(default=False, help_text='heated_orvm supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='hill_assist',
            field=models.BooleanField(default=False, help_text='hill_assist supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='hill_descent_control',
            field=models.BooleanField(default=False, help_text='hill_descent_control supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='mild_hybrid',
            field=models.BooleanField(default=False, help_text='mild_hybrid supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='night_vision_assist',
            field=models.BooleanField(default=False, help_text='night_vision_assist supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='real_time_vehicle_tracking',
            field=models.BooleanField(default=False, help_text='real_time_vehicle_tracking supported or not.'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='tyre_pressure_monitoring_system',
            field=models.BooleanField(default=False, help_text='tyre_pressure_monitoring_system supported or not.'),
        ),
        migrations.AlterField(
            model_name='carperfomance',
            name='acceleration',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True, verbose_name='Acceleration'),
        ),
        migrations.AlterField(
            model_name='carperfomance',
            name='engine_capacity',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4, null=True, verbose_name='Engine Capacity'),
        ),
        migrations.AlterField(
            model_name='carperfomance',
            name='fuel_economy',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fuel Economy'),
        ),
        migrations.AlterField(
            model_name='carperfomance',
            name='top_speed',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Top Speed'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='airbags',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Airbags'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='antilock_braking_system',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='ABS'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='electronic_stability_control',
            field=models.BooleanField(default=False, help_text='electronic stability control supported or not.'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='number_of_airbags',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Number of Airbags'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='rearview_camera',
            field=models.BooleanField(default=False, help_text='rearview camera supported or not.'),
        ),
    ]
