# Generated by Django 3.2.12 on 2023-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230327_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimension',
            name='height',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='cardimension',
            name='length',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cardimension',
            name='width',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Width'),
        ),
    ]
