# Generated by Django 3.2.12 on 2023-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230327_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carperfomance',
            name='acceleration',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Acceleration'),
        ),
    ]
