# Generated by Django 3.2.12 on 2023-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_carperfomance_acceleration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsafety',
            name='number_of_airbags',
        ),
        migrations.AddField(
            model_name='carsafety',
            name='total_number_of_airbags',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name=' Total Number of Airbags'),
        ),
    ]
