# Generated by Django 3.2.12 on 2023-03-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_carfeature_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimension',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car'),
        ),
        migrations.AlterField(
            model_name='carperfomance',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car'),
        ),
        migrations.AlterField(
            model_name='carsafety',
            name='car_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car'),
        ),
    ]
